package com.rexchain.cinema.service;
import com.rexchain.cinema.entity.Booking; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.web.client.RestClient; import java.util.*;
@Service
public class MomoPaymentService{
 private final RestClient client=RestClient.create(); private final String endpoint,partnerCode,accessKey,secretKey,baseUrl;
 public MomoPaymentService(@Value("${payment.momo.endpoint}")String endpoint,@Value("${payment.momo.partner-code:}")String partnerCode,@Value("${payment.momo.access-key:}")String accessKey,@Value("${payment.momo.secret-key:}")String secretKey,@Value("${payment.base-url:http://localhost:8080}")String baseUrl){this.endpoint=endpoint;this.partnerCode=partnerCode;this.accessKey=accessKey;this.secretKey=secretKey;this.baseUrl=baseUrl;}
 public boolean configured(){return !partnerCode.isBlank()&&!accessKey.isBlank()&&!secretKey.isBlank();}
 public String createPaymentUrl(Booking b){if(!configured())throw new IllegalStateException("Chưa cấu hình MoMo sandbox credentials");String requestId=b.getBookingCode()+System.currentTimeMillis();String orderId=b.getBookingCode();String amount=b.getTotalAmount().toBigInteger().toString();String orderInfo="Thanh toan ve "+b.getBookingCode();String redirectUrl=baseUrl+"/payment/callback/momo";String ipnUrl=baseUrl+"/payment/callback/momo/ipn";String extraData="";String requestType="captureWallet";String raw="accessKey="+accessKey+"&amount="+amount+"&extraData="+extraData+"&ipnUrl="+ipnUrl+"&orderId="+orderId+"&orderInfo="+orderInfo+"&partnerCode="+partnerCode+"&redirectUrl="+redirectUrl+"&requestId="+requestId+"&requestType="+requestType;String signature=CryptoUtil.hmac("HmacSHA256",secretKey,raw);Map<String,Object> body=new LinkedHashMap<>();body.put("partnerCode",partnerCode);body.put("requestType",requestType);body.put("ipnUrl",ipnUrl);body.put("redirectUrl",redirectUrl);body.put("orderId",orderId);body.put("amount",Long.parseLong(amount));body.put("orderInfo",orderInfo);body.put("requestId",requestId);body.put("extraData",extraData);body.put("lang","vi");body.put("autoCapture",true);body.put("signature",signature);Map<?,?> response=client.post().uri(endpoint).body(body).retrieve().body(Map.class);if(response==null||!Objects.equals(String.valueOf(response.get("resultCode")),"0"))throw new IllegalStateException("MoMo không tạo được giao dịch: "+(response==null?"no response":response.get("message")));Object payUrl=response.get("payUrl");if(payUrl==null)throw new IllegalStateException("MoMo không trả payUrl");return String.valueOf(payUrl);}
 public boolean verifyResult(Map<String,?> p){try{String raw="accessKey="+accessKey+"&amount="+v(p,"amount")+"&extraData="+v(p,"extraData")+"&message="+v(p,"message")+"&orderId="+v(p,"orderId")+"&orderInfo="+v(p,"orderInfo")+"&orderType="+v(p,"orderType")+"&partnerCode="+v(p,"partnerCode")+"&payType="+v(p,"payType")+"&requestId="+v(p,"requestId")+"&responseTime="+v(p,"responseTime")+"&resultCode="+v(p,"resultCode")+"&transId="+v(p,"transId");return CryptoUtil.hmac("HmacSHA256",secretKey,raw).equalsIgnoreCase(v(p,"signature"));}catch(Exception e){return false;}}
 private String v(Map<String,?> p,String k){Object x=p.get(k);return x==null?"":String.valueOf(x);}
}
