package com.rexchain.cinema.service;
import com.rexchain.cinema.entity.Booking; import jakarta.servlet.http.HttpServletRequest; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;
@Service
public class VnpayPaymentService{
 private final String paymentUrl,tmnCode,hashSecret,baseUrl;
 public VnpayPaymentService(@Value("${payment.vnpay.url}")String paymentUrl,@Value("${payment.vnpay.tmn-code:}")String tmnCode,@Value("${payment.vnpay.hash-secret:}")String hashSecret,@Value("${payment.base-url:http://localhost:8080}")String baseUrl){this.paymentUrl=paymentUrl;this.tmnCode=tmnCode;this.hashSecret=hashSecret;this.baseUrl=baseUrl;}
 public boolean configured(){return !tmnCode.isBlank()&&!hashSecret.isBlank();}
 public String createPaymentUrl(Booking b,HttpServletRequest req){if(!configured())throw new IllegalStateException("Chưa cấu hình VNPAY sandbox credentials");ZoneId zone=ZoneId.of("Asia/Ho_Chi_Minh");LocalDateTime now=LocalDateTime.now(zone);DateTimeFormatter fmt=DateTimeFormatter.ofPattern("yyyyMMddHHmmss");Map<String,String> p=new TreeMap<>();p.put("vnp_Version","2.1.0");p.put("vnp_Command","pay");p.put("vnp_TmnCode",tmnCode);p.put("vnp_Amount",b.getTotalAmount().multiply(java.math.BigDecimal.valueOf(100)).toBigInteger().toString());p.put("vnp_CurrCode","VND");p.put("vnp_TxnRef",b.getBookingCode());p.put("vnp_OrderInfo","Thanh toan ve "+b.getBookingCode());p.put("vnp_OrderType","other");p.put("vnp_Locale","vn");p.put("vnp_ReturnUrl",baseUrl+"/payment/callback/vnpay");p.put("vnp_IpAddr",clientIp(req));p.put("vnp_CreateDate",now.format(fmt));p.put("vnp_ExpireDate",now.plusMinutes(15).format(fmt));String hashData=raw(p);String query=query(p);return paymentUrl+"?"+query+"&vnp_SecureHash="+CryptoUtil.hmac("HmacSHA512",hashSecret,hashData);}
 public boolean verify(Map<String,String> input){String supplied=input.get("vnp_SecureHash");if(supplied==null)return false;Map<String,String> p=new TreeMap<>();input.forEach((k,v)->{if(k.startsWith("vnp_")&&!k.equals("vnp_SecureHash")&&!k.equals("vnp_SecureHashType")&&v!=null&&!v.isBlank())p.put(k,v);});return CryptoUtil.hmac("HmacSHA512",hashSecret,raw(p)).equalsIgnoreCase(supplied);}
 private String raw(Map<String,String> p){return p.entrySet().stream().filter(e->e.getValue()!=null&&!e.getValue().isBlank()).map(e->e.getKey()+"="+e.getValue()).reduce((a,b)->a+"&"+b).orElse("");}
 private String query(Map<String,String> p){return p.entrySet().stream().filter(e->e.getValue()!=null&&!e.getValue().isBlank()).map(e->enc(e.getKey())+"="+enc(e.getValue())).reduce((a,b)->a+"&"+b).orElse("");}
 private String enc(String s){return URLEncoder.encode(s,StandardCharsets.US_ASCII);}
 private String clientIp(HttpServletRequest r){String x=r.getHeader("X-Forwarded-For");if(x!=null&&!x.isBlank())return x.split(",")[0].trim();return r.getRemoteAddr()==null?"127.0.0.1":r.getRemoteAddr();}
}
